cloud:
  aws:
    credentials:
      access-key: AKIA5ELYTBTPD5O2GDAP
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: utilstuff-reverb-2020

server:
  port: 9090